apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod    

---
apiVersion: v1
kind: Namespace
metadata:
  name: stage1
  labels:
    name: stage1       
---
apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    name: testing           