apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-my-app
  namespace: development
spec:
  replicas: 4
  selector:
    matchLabels:
      app: development
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80